
@baseUrl = http://localhost:5000/api
@token = {{login.response.body.token}}

### Register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "email": "user2@example.com",
  "password": "password789"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "user2@example.com",
  "password": "password789"
}

### Get Categories
GET {{baseUrl}}/transactions/categories
Authorization: Bearer {{token}}

### Create Transaction
POST {{baseUrl}}/transactions
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "expense",
  "category_id": 6,
  "amount": 1300,
  "description": "Salary"
}

### Get All Transactions
GET {{baseUrl}}/transactions?page=1&limit=10
Authorization: Bearer {{token}}

### Get Transaction by ID
GET {{baseUrl}}/transactions/4
Authorization: Bearer {{token}}

### Update Transaction
PUT {{baseUrl}}/transactions/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "type": "income",
  "category_id": 1,
  "amount": 1500,
  "description": "Updated salary"
}

### Delete Transaction
DELETE {{baseUrl}}/transactions/3
Authorization: Bearer {{token}}

### Get Summary
GET {{baseUrl}}/reports/summary
Authorization: Bearer {{token}}

### Get Monthly Report
GET {{baseUrl}}/reports/monthly?year=2024&month=11
Authorization: Bearer {{token}}

### Get Category Report
GET {{baseUrl}}/reports/category
Authorization: Bearer {{token}}